CREATE TABLE IF NOT EXISTS comments
(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    text TEXT NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    image VARCHAR(100) NOT NULL DEFAULT 'no-user.jpg'
) ENGINE=InnoDB DEFAULT CHARSET utf8;